# Generated by Django 4.0.2 on 2022-02-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-recommendation']},
        ),
    ]
