# Generated by Django 4.0.2 on 2022-02-27 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_comment_options_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='solved_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='solved_explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='solved_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='solved_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
