# Generated by Django 4.0.2 on 2022-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_solved_created_at_report_solved_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='solved_app_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='solved_google_profile_image',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='solved_user',
            field=models.TextField(default='', max_length=30),
        ),
    ]
