# Generated by Django 4.0.2 on 2022-03-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_solved_app_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='solved_user',
            field=models.TextField(db_index=True, default='', max_length=30),
        ),
    ]
