# Generated by Django 4.0.2 on 2022-02-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_name',
            field=models.CharField(max_length=100),
        ),
    ]
