# Generated by Django 4.0.2 on 2022-02-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_google_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_profile_image',
            field=models.CharField(max_length=100),
        ),
    ]
