# Generated by Django 4.0.2 on 2022-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_profile_image',
            field=models.CharField(max_length=500),
        ),
    ]
